#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Yuna Isomura
#SPDX-License-Identifier:BSD-3-Clause

import sys

def fibo_num(n):
    a, b = 1, 1 #最初のフィボナッチ数

    if n >= 1:
        print(a, end=" ")#第1項

    if n >= 2:
        print(b, end=" ")#第2項

    for _ in range(3, n + 1):#第3項以降
        next_num = a + b
        print(next_num, end=" ")
        a, b = b, next_num

    print()

if __name__ == "__main__":
    input_line = sys.stdin.read().strip()

    if not input_line.isdigit():
        sys.exit(1)

    n = int(input_line)
    if n <= 0:
        sys.exit(1)

fibo_num(n)
